"""strip information

Revision ID: 8d22804670f5
Revises: 
Create Date: 2021-10-04 23:24:10.038572+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d22804670f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pixels",
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("r", sa.Integer(), nullable=False),
        sa.Column("g", sa.Integer(), nullable=False),
        sa.Column("b", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("index"),
    )
    op.create_index(op.f("ix_pixels_index"), "pixels", ["index"], unique=False)
    op.create_table(
        "strips",
        sa.Column(
            "attribute",
            sa.Enum("brightness", "mode", name="attribute"),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("attribute"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("strips")
    op.drop_index(op.f("ix_pixels_index"), table_name="pixels")
    op.drop_table("pixels")
    # ### end Alembic commands ###
