[tool.poetry]
name = "lights"
version = "0.1.0"
description = "Control an Adafruit NeoPixel light strip from a Raspberry Pi"
authors = ["Alex Krantz <alex@krantz.dev>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pycapnp = "^1.1.0"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
black = "^21.9b0"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
