[tool.poetry]
name = "lights"
version = "0.1.0"
description = "Control an Adafruit NeoPixel light strip from a Raspberry Pi"
authors = ["Alex Krantz <alex@krantz.dev>"]
license = "MIT"
packages = [
    { include = "lights_common" },
    { include = "lights_controller" },
]

[tool.poetry.dependencies]
python = "^3.7"
pycapnp = "^1.1.0"
click = "^8.0.1"
"RPi.GPIO" = "^0.7.0"
Adafruit-Blinka = "^6.13.1"
rpi-ws281x = "^4.3.0"
adafruit-circuitpython-neopixel = "^6.2.1"

[tool.poetry.dev-dependencies]
black = "^21.9b0"

[tool.poetry.scripts]
lights-controller = "lights_controller.main:main"

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
