# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lights.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="lights.proto",
    package="lights",
    syntax="proto3",
    serialized_options=b"Z0github.com/akrantz01/lights/lights-web/lights/pb",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0clights.proto\x12\x06lights"(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r"8\n\x07SetArgs\x12\x0f\n\x07indexes\x18\x01 \x03(\r\x12\x1c\n\x05\x63olor\x18\x02 \x01(\x0b\x32\r.lights.Color"+\n\nSetAllArgs\x12\x1d\n\x06\x63olors\x18\x01 \x03(\x0b\x32\r.lights.Color"$\n\x0e\x42rightnessArgs\x12\x12\n\nbrightness\x18\x01 \x01(\r" \n\x12StartAnimationArgs\x12\n\n\x02id\x18\x01 \x01(\t"V\n\x15RegisterAnimationArgs\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12#\n\x04kind\x18\x03 \x01(\x0e\x32\x15.lights.AnimationKind""\n\x0f\x41nimationStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08"%\n\x17UnregisterAnimationArgs\x12\n\n\x02id\x18\x01 \x01(\t"\x07\n\x05\x45mpty*0\n\rAnimationKind\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04WASM\x10\x01\x12\x08\n\x04\x46LOW\x10\x02\x32\xcb\x03\n\nController\x12\'\n\x03Set\x12\x0f.lights.SetArgs\x1a\r.lights.Empty"\x00\x12-\n\x06SetAll\x12\x12.lights.SetAllArgs\x1a\r.lights.Empty"\x00\x12&\n\x04\x46ill\x12\r.lights.Color\x1a\r.lights.Empty"\x00\x12\x35\n\nBrightness\x12\x16.lights.BrightnessArgs\x1a\r.lights.Empty"\x00\x12=\n\x0eStartAnimation\x12\x1a.lights.StartAnimationArgs\x1a\r.lights.Empty"\x00\x12/\n\rStopAnimation\x12\r.lights.Empty\x1a\r.lights.Empty"\x00\x12M\n\x11RegisterAnimation\x12\x1d.lights.RegisterAnimationArgs\x1a\x17.lights.AnimationStatus"\x00\x12G\n\x13UnregisterAnimation\x12\x1f.lights.UnregisterAnimationArgs\x1a\r.lights.Empty"\x00\x42\x32Z0github.com/akrantz01/lights/lights-web/lights/pbb\x06proto3',
)

_ANIMATIONKIND = _descriptor.EnumDescriptor(
    name="AnimationKind",
    full_name="lights.AnimationKind",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="UNKNOWN",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="WASM",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="FLOW",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=413,
    serialized_end=461,
)
_sym_db.RegisterEnumDescriptor(_ANIMATIONKIND)

AnimationKind = enum_type_wrapper.EnumTypeWrapper(_ANIMATIONKIND)
UNKNOWN = 0
WASM = 1
FLOW = 2


_COLOR = _descriptor.Descriptor(
    name="Color",
    full_name="lights.Color",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="r",
            full_name="lights.Color.r",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="g",
            full_name="lights.Color.g",
            index=1,
            number=2,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="b",
            full_name="lights.Color.b",
            index=2,
            number=3,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=24,
    serialized_end=64,
)


_SETARGS = _descriptor.Descriptor(
    name="SetArgs",
    full_name="lights.SetArgs",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="indexes",
            full_name="lights.SetArgs.indexes",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="color",
            full_name="lights.SetArgs.color",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=66,
    serialized_end=122,
)


_SETALLARGS = _descriptor.Descriptor(
    name="SetAllArgs",
    full_name="lights.SetAllArgs",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="colors",
            full_name="lights.SetAllArgs.colors",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=124,
    serialized_end=167,
)


_BRIGHTNESSARGS = _descriptor.Descriptor(
    name="BrightnessArgs",
    full_name="lights.BrightnessArgs",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="brightness",
            full_name="lights.BrightnessArgs.brightness",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=169,
    serialized_end=205,
)


_STARTANIMATIONARGS = _descriptor.Descriptor(
    name="StartAnimationArgs",
    full_name="lights.StartAnimationArgs",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="lights.StartAnimationArgs.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=207,
    serialized_end=239,
)


_REGISTERANIMATIONARGS = _descriptor.Descriptor(
    name="RegisterAnimationArgs",
    full_name="lights.RegisterAnimationArgs",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="lights.RegisterAnimationArgs.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="data",
            full_name="lights.RegisterAnimationArgs.data",
            index=1,
            number=2,
            type=12,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"",
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="kind",
            full_name="lights.RegisterAnimationArgs.kind",
            index=2,
            number=3,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=241,
    serialized_end=327,
)


_ANIMATIONSTATUS = _descriptor.Descriptor(
    name="AnimationStatus",
    full_name="lights.AnimationStatus",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="success",
            full_name="lights.AnimationStatus.success",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=329,
    serialized_end=363,
)


_UNREGISTERANIMATIONARGS = _descriptor.Descriptor(
    name="UnregisterAnimationArgs",
    full_name="lights.UnregisterAnimationArgs",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="id",
            full_name="lights.UnregisterAnimationArgs.id",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=365,
    serialized_end=402,
)


_EMPTY = _descriptor.Descriptor(
    name="Empty",
    full_name="lights.Empty",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=404,
    serialized_end=411,
)

_SETARGS.fields_by_name["color"].message_type = _COLOR
_SETALLARGS.fields_by_name["colors"].message_type = _COLOR
_REGISTERANIMATIONARGS.fields_by_name["kind"].enum_type = _ANIMATIONKIND
DESCRIPTOR.message_types_by_name["Color"] = _COLOR
DESCRIPTOR.message_types_by_name["SetArgs"] = _SETARGS
DESCRIPTOR.message_types_by_name["SetAllArgs"] = _SETALLARGS
DESCRIPTOR.message_types_by_name["BrightnessArgs"] = _BRIGHTNESSARGS
DESCRIPTOR.message_types_by_name["StartAnimationArgs"] = _STARTANIMATIONARGS
DESCRIPTOR.message_types_by_name["RegisterAnimationArgs"] = _REGISTERANIMATIONARGS
DESCRIPTOR.message_types_by_name["AnimationStatus"] = _ANIMATIONSTATUS
DESCRIPTOR.message_types_by_name["UnregisterAnimationArgs"] = _UNREGISTERANIMATIONARGS
DESCRIPTOR.message_types_by_name["Empty"] = _EMPTY
DESCRIPTOR.enum_types_by_name["AnimationKind"] = _ANIMATIONKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Color = _reflection.GeneratedProtocolMessageType(
    "Color",
    (_message.Message,),
    {
        "DESCRIPTOR": _COLOR,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.Color)
    },
)
_sym_db.RegisterMessage(Color)

SetArgs = _reflection.GeneratedProtocolMessageType(
    "SetArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _SETARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.SetArgs)
    },
)
_sym_db.RegisterMessage(SetArgs)

SetAllArgs = _reflection.GeneratedProtocolMessageType(
    "SetAllArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _SETALLARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.SetAllArgs)
    },
)
_sym_db.RegisterMessage(SetAllArgs)

BrightnessArgs = _reflection.GeneratedProtocolMessageType(
    "BrightnessArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _BRIGHTNESSARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.BrightnessArgs)
    },
)
_sym_db.RegisterMessage(BrightnessArgs)

StartAnimationArgs = _reflection.GeneratedProtocolMessageType(
    "StartAnimationArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _STARTANIMATIONARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.StartAnimationArgs)
    },
)
_sym_db.RegisterMessage(StartAnimationArgs)

RegisterAnimationArgs = _reflection.GeneratedProtocolMessageType(
    "RegisterAnimationArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERANIMATIONARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.RegisterAnimationArgs)
    },
)
_sym_db.RegisterMessage(RegisterAnimationArgs)

AnimationStatus = _reflection.GeneratedProtocolMessageType(
    "AnimationStatus",
    (_message.Message,),
    {
        "DESCRIPTOR": _ANIMATIONSTATUS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.AnimationStatus)
    },
)
_sym_db.RegisterMessage(AnimationStatus)

UnregisterAnimationArgs = _reflection.GeneratedProtocolMessageType(
    "UnregisterAnimationArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNREGISTERANIMATIONARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.UnregisterAnimationArgs)
    },
)
_sym_db.RegisterMessage(UnregisterAnimationArgs)

Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.Empty)
    },
)
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_CONTROLLER = _descriptor.ServiceDescriptor(
    name="Controller",
    full_name="lights.Controller",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=464,
    serialized_end=923,
    methods=[
        _descriptor.MethodDescriptor(
            name="Set",
            full_name="lights.Controller.Set",
            index=0,
            containing_service=None,
            input_type=_SETARGS,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="SetAll",
            full_name="lights.Controller.SetAll",
            index=1,
            containing_service=None,
            input_type=_SETALLARGS,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Fill",
            full_name="lights.Controller.Fill",
            index=2,
            containing_service=None,
            input_type=_COLOR,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="Brightness",
            full_name="lights.Controller.Brightness",
            index=3,
            containing_service=None,
            input_type=_BRIGHTNESSARGS,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="StartAnimation",
            full_name="lights.Controller.StartAnimation",
            index=4,
            containing_service=None,
            input_type=_STARTANIMATIONARGS,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="StopAnimation",
            full_name="lights.Controller.StopAnimation",
            index=5,
            containing_service=None,
            input_type=_EMPTY,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="RegisterAnimation",
            full_name="lights.Controller.RegisterAnimation",
            index=6,
            containing_service=None,
            input_type=_REGISTERANIMATIONARGS,
            output_type=_ANIMATIONSTATUS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="UnregisterAnimation",
            full_name="lights.Controller.UnregisterAnimation",
            index=7,
            containing_service=None,
            input_type=_UNREGISTERANIMATIONARGS,
            output_type=_EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_CONTROLLER)

DESCRIPTOR.services_by_name["Controller"] = _CONTROLLER

# @@protoc_insertion_point(module_scope)
