# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lights.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0clights.proto\x12\x06lights"(\n\x05\x43olor\x12\t\n\x01r\x18\x01 \x01(\r\x12\t\n\x01g\x18\x02 \x01(\r\x12\t\n\x01\x62\x18\x03 \x01(\r"8\n\x07SetArgs\x12\x0f\n\x07indexes\x18\x01 \x03(\r\x12\x1c\n\x05\x63olor\x18\x02 \x01(\x0b\x32\r.lights.Color"+\n\nSetAllArgs\x12\x1d\n\x06\x63olors\x18\x01 \x03(\x0b\x32\r.lights.Color"$\n\x0e\x42rightnessArgs\x12\x12\n\nbrightness\x18\x01 \x01(\r" \n\x12StartAnimationArgs\x12\n\n\x02id\x18\x01 \x01(\t"1\n\x15RegisterAnimationArgs\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04wasm\x18\x02 \x01(\x0c""\n\x0f\x41nimationStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08"%\n\x17UnregisterAnimationArgs\x12\n\n\x02id\x18\x01 \x01(\t"\x07\n\x05\x45mpty2\xcb\x03\n\nController\x12\'\n\x03Set\x12\x0f.lights.SetArgs\x1a\r.lights.Empty"\x00\x12-\n\x06SetAll\x12\x12.lights.SetAllArgs\x1a\r.lights.Empty"\x00\x12&\n\x04\x46ill\x12\r.lights.Color\x1a\r.lights.Empty"\x00\x12\x35\n\nBrightness\x12\x16.lights.BrightnessArgs\x1a\r.lights.Empty"\x00\x12=\n\x0eStartAnimation\x12\x1a.lights.StartAnimationArgs\x1a\r.lights.Empty"\x00\x12/\n\rStopAnimation\x12\r.lights.Empty\x1a\r.lights.Empty"\x00\x12M\n\x11RegisterAnimation\x12\x1d.lights.RegisterAnimationArgs\x1a\x17.lights.AnimationStatus"\x00\x12G\n\x13UnregisterAnimation\x12\x1f.lights.UnregisterAnimationArgs\x1a\r.lights.Empty"\x00\x62\x06proto3'
)


_COLOR = DESCRIPTOR.message_types_by_name["Color"]
_SETARGS = DESCRIPTOR.message_types_by_name["SetArgs"]
_SETALLARGS = DESCRIPTOR.message_types_by_name["SetAllArgs"]
_BRIGHTNESSARGS = DESCRIPTOR.message_types_by_name["BrightnessArgs"]
_STARTANIMATIONARGS = DESCRIPTOR.message_types_by_name["StartAnimationArgs"]
_REGISTERANIMATIONARGS = DESCRIPTOR.message_types_by_name["RegisterAnimationArgs"]
_ANIMATIONSTATUS = DESCRIPTOR.message_types_by_name["AnimationStatus"]
_UNREGISTERANIMATIONARGS = DESCRIPTOR.message_types_by_name["UnregisterAnimationArgs"]
_EMPTY = DESCRIPTOR.message_types_by_name["Empty"]
Color = _reflection.GeneratedProtocolMessageType(
    "Color",
    (_message.Message,),
    {
        "DESCRIPTOR": _COLOR,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.Color)
    },
)
_sym_db.RegisterMessage(Color)

SetArgs = _reflection.GeneratedProtocolMessageType(
    "SetArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _SETARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.SetArgs)
    },
)
_sym_db.RegisterMessage(SetArgs)

SetAllArgs = _reflection.GeneratedProtocolMessageType(
    "SetAllArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _SETALLARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.SetAllArgs)
    },
)
_sym_db.RegisterMessage(SetAllArgs)

BrightnessArgs = _reflection.GeneratedProtocolMessageType(
    "BrightnessArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _BRIGHTNESSARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.BrightnessArgs)
    },
)
_sym_db.RegisterMessage(BrightnessArgs)

StartAnimationArgs = _reflection.GeneratedProtocolMessageType(
    "StartAnimationArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _STARTANIMATIONARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.StartAnimationArgs)
    },
)
_sym_db.RegisterMessage(StartAnimationArgs)

RegisterAnimationArgs = _reflection.GeneratedProtocolMessageType(
    "RegisterAnimationArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _REGISTERANIMATIONARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.RegisterAnimationArgs)
    },
)
_sym_db.RegisterMessage(RegisterAnimationArgs)

AnimationStatus = _reflection.GeneratedProtocolMessageType(
    "AnimationStatus",
    (_message.Message,),
    {
        "DESCRIPTOR": _ANIMATIONSTATUS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.AnimationStatus)
    },
)
_sym_db.RegisterMessage(AnimationStatus)

UnregisterAnimationArgs = _reflection.GeneratedProtocolMessageType(
    "UnregisterAnimationArgs",
    (_message.Message,),
    {
        "DESCRIPTOR": _UNREGISTERANIMATIONARGS,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.UnregisterAnimationArgs)
    },
)
_sym_db.RegisterMessage(UnregisterAnimationArgs)

Empty = _reflection.GeneratedProtocolMessageType(
    "Empty",
    (_message.Message,),
    {
        "DESCRIPTOR": _EMPTY,
        "__module__": "lights_pb2"
        # @@protoc_insertion_point(class_scope:lights.Empty)
    },
)
_sym_db.RegisterMessage(Empty)

_CONTROLLER = DESCRIPTOR.services_by_name["Controller"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _COLOR._serialized_start = 24
    _COLOR._serialized_end = 64
    _SETARGS._serialized_start = 66
    _SETARGS._serialized_end = 122
    _SETALLARGS._serialized_start = 124
    _SETALLARGS._serialized_end = 167
    _BRIGHTNESSARGS._serialized_start = 169
    _BRIGHTNESSARGS._serialized_end = 205
    _STARTANIMATIONARGS._serialized_start = 207
    _STARTANIMATIONARGS._serialized_end = 239
    _REGISTERANIMATIONARGS._serialized_start = 241
    _REGISTERANIMATIONARGS._serialized_end = 290
    _ANIMATIONSTATUS._serialized_start = 292
    _ANIMATIONSTATUS._serialized_end = 326
    _UNREGISTERANIMATIONARGS._serialized_start = 328
    _UNREGISTERANIMATIONARGS._serialized_end = 365
    _EMPTY._serialized_start = 367
    _EMPTY._serialized_end = 374
    _CONTROLLER._serialized_start = 377
    _CONTROLLER._serialized_end = 836
# @@protoc_insertion_point(module_scope)
