// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: lights.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// What type of animation to register
type AnimationKind int32

const (
	AnimationKind_UNKNOWN AnimationKind = 0
	AnimationKind_WASM    AnimationKind = 1
	AnimationKind_FLOW    AnimationKind = 2
)

// Enum value maps for AnimationKind.
var (
	AnimationKind_name = map[int32]string{
		0: "UNKNOWN",
		1: "WASM",
		2: "FLOW",
	}
	AnimationKind_value = map[string]int32{
		"UNKNOWN": 0,
		"WASM":    1,
		"FLOW":    2,
	}
)

func (x AnimationKind) Enum() *AnimationKind {
	p := new(AnimationKind)
	*p = x
	return p
}

func (x AnimationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AnimationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_lights_proto_enumTypes[0].Descriptor()
}

func (AnimationKind) Type() protoreflect.EnumType {
	return &file_lights_proto_enumTypes[0]
}

func (x AnimationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AnimationKind.Descriptor instead.
func (AnimationKind) EnumDescriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{0}
}

// An RGB color with values in the range 0-255 inclusive.
type Color struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R uint32 `protobuf:"varint,1,opt,name=r,proto3" json:"r,omitempty"`
	G uint32 `protobuf:"varint,2,opt,name=g,proto3" json:"g,omitempty"`
	B uint32 `protobuf:"varint,3,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Color) Reset() {
	*x = Color{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{0}
}

func (x *Color) GetR() uint32 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Color) GetG() uint32 {
	if x != nil {
		return x.G
	}
	return 0
}

func (x *Color) GetB() uint32 {
	if x != nil {
		return x.B
	}
	return 0
}

// The arguments for the Set method
type SetArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Indexes []uint32 `protobuf:"varint,1,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`
	Color   *Color   `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *SetArgs) Reset() {
	*x = SetArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetArgs) ProtoMessage() {}

func (x *SetArgs) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetArgs.ProtoReflect.Descriptor instead.
func (*SetArgs) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{1}
}

func (x *SetArgs) GetIndexes() []uint32 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

func (x *SetArgs) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

// The arguments for the SetAll method
type SetAllArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Colors []*Color `protobuf:"bytes,1,rep,name=colors,proto3" json:"colors,omitempty"`
}

func (x *SetAllArgs) Reset() {
	*x = SetAllArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAllArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAllArgs) ProtoMessage() {}

func (x *SetAllArgs) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAllArgs.ProtoReflect.Descriptor instead.
func (*SetAllArgs) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{2}
}

func (x *SetAllArgs) GetColors() []*Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

// The arguments for the Brightness method
type BrightnessArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brightness uint32 `protobuf:"varint,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
}

func (x *BrightnessArgs) Reset() {
	*x = BrightnessArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BrightnessArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrightnessArgs) ProtoMessage() {}

func (x *BrightnessArgs) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrightnessArgs.ProtoReflect.Descriptor instead.
func (*BrightnessArgs) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{3}
}

func (x *BrightnessArgs) GetBrightness() uint32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

// The arguments for the StartAnimation method
type StartAnimationArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *StartAnimationArgs) Reset() {
	*x = StartAnimationArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartAnimationArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAnimationArgs) ProtoMessage() {}

func (x *StartAnimationArgs) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAnimationArgs.ProtoReflect.Descriptor instead.
func (*StartAnimationArgs) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{4}
}

func (x *StartAnimationArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// The arguments for the RegisterAnimation method
type RegisterAnimationArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data []byte        `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Kind AnimationKind `protobuf:"varint,3,opt,name=kind,proto3,enum=lights.AnimationKind" json:"kind,omitempty"`
}

func (x *RegisterAnimationArgs) Reset() {
	*x = RegisterAnimationArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterAnimationArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAnimationArgs) ProtoMessage() {}

func (x *RegisterAnimationArgs) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAnimationArgs.ProtoReflect.Descriptor instead.
func (*RegisterAnimationArgs) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterAnimationArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterAnimationArgs) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RegisterAnimationArgs) GetKind() AnimationKind {
	if x != nil {
		return x.Kind
	}
	return AnimationKind_UNKNOWN
}

// The return type for the RegisterAnimation method
type AnimationStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *AnimationStatus) Reset() {
	*x = AnimationStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimationStatus) ProtoMessage() {}

func (x *AnimationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimationStatus.ProtoReflect.Descriptor instead.
func (*AnimationStatus) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{6}
}

func (x *AnimationStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// The arguments for the UnregisterAnimation method
type UnregisterAnimationArgs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UnregisterAnimationArgs) Reset() {
	*x = UnregisterAnimationArgs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnregisterAnimationArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterAnimationArgs) ProtoMessage() {}

func (x *UnregisterAnimationArgs) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterAnimationArgs.ProtoReflect.Descriptor instead.
func (*UnregisterAnimationArgs) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{7}
}

func (x *UnregisterAnimationArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// An empty message used for RPC messages
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_lights_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_lights_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_lights_proto_rawDescGZIP(), []int{8}
}

var File_lights_proto protoreflect.FileDescriptor

var file_lights_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x22, 0x31, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12,
	0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x72, 0x12, 0x0c, 0x0a,
	0x01, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x67, 0x12, 0x0c, 0x0a, 0x01, 0x62,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x62, 0x22, 0x48, 0x0a, 0x07, 0x53, 0x65, 0x74,
	0x41, 0x72, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x07, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x12, 0x23,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x52, 0x05, 0x63, 0x6f,
	0x6c, 0x6f, 0x72, 0x22, 0x33, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x72, 0x67,
	0x73, 0x12, 0x25, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x52, 0x06, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x22, 0x30, 0x0a, 0x0e, 0x42, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x41, 0x72, 0x67, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x62, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x22, 0x24, 0x0a, 0x12, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x66, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x29, 0x0a,
	0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6c, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x69,
	0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x29, 0x0a, 0x17, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x2a, 0x30, 0x0a, 0x0d, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e,
	0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x57, 0x41, 0x53, 0x4d, 0x10,
	0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x4c, 0x4f, 0x57, 0x10, 0x02, 0x32, 0xcb, 0x03, 0x0a, 0x0a,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x03, 0x53, 0x65,
	0x74, 0x12, 0x0f, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x72,
	0x67, 0x73, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x12, 0x12, 0x2e,
	0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x72, 0x67,
	0x73, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x26, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x6c, 0x12, 0x0d, 0x2e, 0x6c, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x2e, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x0a, 0x42, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x12, 0x16, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x2e, 0x42, 0x72, 0x69, 0x67, 0x68, 0x74, 0x6e, 0x65, 0x73, 0x73, 0x41, 0x72, 0x67, 0x73,
	0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x3d, 0x0a, 0x0e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x1a,
	0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x0d, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x4d, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x17, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2e, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x13, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x41, 0x72, 0x67, 0x73, 0x1a, 0x0d, 0x2e, 0x6c, 0x69, 0x67, 0x68, 0x74,
	0x73, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6b, 0x72, 0x61, 0x6e, 0x74, 0x7a, 0x30,
	0x31, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2d,
	0x77, 0x65, 0x62, 0x2f, 0x6c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lights_proto_rawDescOnce sync.Once
	file_lights_proto_rawDescData = file_lights_proto_rawDesc
)

func file_lights_proto_rawDescGZIP() []byte {
	file_lights_proto_rawDescOnce.Do(func() {
		file_lights_proto_rawDescData = protoimpl.X.CompressGZIP(file_lights_proto_rawDescData)
	})
	return file_lights_proto_rawDescData
}

var file_lights_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_lights_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_lights_proto_goTypes = []interface{}{
	(AnimationKind)(0),              // 0: lights.AnimationKind
	(*Color)(nil),                   // 1: lights.Color
	(*SetArgs)(nil),                 // 2: lights.SetArgs
	(*SetAllArgs)(nil),              // 3: lights.SetAllArgs
	(*BrightnessArgs)(nil),          // 4: lights.BrightnessArgs
	(*StartAnimationArgs)(nil),      // 5: lights.StartAnimationArgs
	(*RegisterAnimationArgs)(nil),   // 6: lights.RegisterAnimationArgs
	(*AnimationStatus)(nil),         // 7: lights.AnimationStatus
	(*UnregisterAnimationArgs)(nil), // 8: lights.UnregisterAnimationArgs
	(*Empty)(nil),                   // 9: lights.Empty
}
var file_lights_proto_depIdxs = []int32{
	1,  // 0: lights.SetArgs.color:type_name -> lights.Color
	1,  // 1: lights.SetAllArgs.colors:type_name -> lights.Color
	0,  // 2: lights.RegisterAnimationArgs.kind:type_name -> lights.AnimationKind
	2,  // 3: lights.Controller.Set:input_type -> lights.SetArgs
	3,  // 4: lights.Controller.SetAll:input_type -> lights.SetAllArgs
	1,  // 5: lights.Controller.Fill:input_type -> lights.Color
	4,  // 6: lights.Controller.Brightness:input_type -> lights.BrightnessArgs
	5,  // 7: lights.Controller.StartAnimation:input_type -> lights.StartAnimationArgs
	9,  // 8: lights.Controller.StopAnimation:input_type -> lights.Empty
	6,  // 9: lights.Controller.RegisterAnimation:input_type -> lights.RegisterAnimationArgs
	8,  // 10: lights.Controller.UnregisterAnimation:input_type -> lights.UnregisterAnimationArgs
	9,  // 11: lights.Controller.Set:output_type -> lights.Empty
	9,  // 12: lights.Controller.SetAll:output_type -> lights.Empty
	9,  // 13: lights.Controller.Fill:output_type -> lights.Empty
	9,  // 14: lights.Controller.Brightness:output_type -> lights.Empty
	9,  // 15: lights.Controller.StartAnimation:output_type -> lights.Empty
	9,  // 16: lights.Controller.StopAnimation:output_type -> lights.Empty
	7,  // 17: lights.Controller.RegisterAnimation:output_type -> lights.AnimationStatus
	9,  // 18: lights.Controller.UnregisterAnimation:output_type -> lights.Empty
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_lights_proto_init() }
func file_lights_proto_init() {
	if File_lights_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_lights_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Color); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAllArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BrightnessArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartAnimationArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterAnimationArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimationStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnregisterAnimationArgs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_lights_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lights_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lights_proto_goTypes,
		DependencyIndexes: file_lights_proto_depIdxs,
		EnumInfos:         file_lights_proto_enumTypes,
		MessageInfos:      file_lights_proto_msgTypes,
	}.Build()
	File_lights_proto = out.File
	file_lights_proto_rawDesc = nil
	file_lights_proto_goTypes = nil
	file_lights_proto_depIdxs = nil
}
