[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["macros", "parking_lot", "rt-multi-thread"] }

dotenv = "0.15.0"

tonic = "0.6.2"
prost = "0.9.0"

[build-dependencies]
tonic-build = "0.6.2"
