on:
  - push

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: api/go.mod
          check-latest: true
          cache: true
          cache-dependency-path: api/go.sum
      - run: GOARCH=${{ matrix.arch }} go build -o ./lights-api.linux-${{ matrix.arch }}
        working-directory: api
      - uses: actions/upload-artifact@v3
        with:
          name: lights-api.linux-${{ matrix.arch }}
          path: ${{ github.workspace }}/api/lights-api.linux-${{ matrix.arch }}

  build-controller:
    name: Build Controller
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - aarch64
          - x86_64
        compiler:
          - any
          - cranelift
          - llvm
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.arch }}-unknown-linux-gnu
      - uses: actions/cache@v3
        id: cache-llvm
        with:
          path: ./llvm
          key: llvm-12
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: 12.0
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - uses: actions/cache@v3
        id: cache-rust
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            controller/target/
          key: ${{ runner.os }}-cargo-controller-${{ matrix.arch }}-${{ hashFiles('controller/Cargo.lock') }}-${{ matrix.compiler }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-controller-${{ matrix.arch }}-${{ hashFiles('controller/Cargo.lock') }}-${{ matrix.compiler }}-
            ${{ runner.os }}-cargo-controller-${{ matrix.arch }}-${{ hashFiles('controller/Cargo.lock') }}-
      # TODO: use latest version instead of main
      - run: cargo install cross --git https://github.com/cross-rs/cross
        if: steps.cache-rust.outputs.cache-hit != 'true'
      - run: cross build --release --target ${{ matrix.arch }}-unknown-linux-gnu --no-default-features --feature ${{ matrix.compiler }}
        working-directory: controller
      - uses: actions/upload-artifact@v3
        with:
          name: lights-controller.${{ matrix.compiler }}.linux-${{ matrix.arch }}
          path: ${{ github.workspace }}/controller/target/${{ matrix.arch }}-unknown-linux-gnu/release/controller

  build-animation:
    name: Build Animation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        animation:
          - rainbow
          - simple
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            sample-animations/${{ matrix.animation }}/target/
          key: ${{ runner.os }}-cargo-${{ matrix.animation }}-${{ hashFiles('sample-animations/${{ matrix.animation }}/Cargo.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.animation }}-${{ hashFiles('sample-animations/${{ matrix.animation }}/Cargo.lock') }}-
      - run: cargo build --release
        working-directory: sample-animations/${{ matrix.animation }}
      - uses: actions/upload-artifact@v3
        with:
          name: animation-${{ matrix.animation }}.wasm
          path: ${{ github.workspace }}/sample-animations/${{ matrix.animation }}/target/wasm32-unknown-unknown/release/${{ matrix.animation }}.wasm
