on:
  - push

jobs:
  api:
    name: Lint API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: api/go.sum
          check-latest: true
          cache: true
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.0
          working-directory: api

  controller:
    name: Lint Controller
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('controller/Cargo.lock') }}
          restore-key: |
            ${{ runner.os }}-cargo-${{ hashFiles('controller/Cargo.lock') }}-
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --check --manifest-path controller/Cargo.toml
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: clippy - controller
          args: --manifest-path controller/Cargo.toml
