name: Pulumi
on:
  push:
    branches:
      - main

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
          cache-dependency-path: setup/yarn.lock
      - run: yarn install
        working-directory: setup
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
          work-dir: setup
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  build-api:
    name: Build API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'
      - run: GOARCH=${{ matrix.arch }} go build -o ./lights-api.linux-${{ matrix.arch }}
      - uses: actions/upload-artifact@v2
        with:
          name: lights-api.linux-${{ matrix.arch }}
          path: ${{ github.workspace }}/lights-api.linux-${{ matrix.arch }}
