on:
  push:
    branches:
      - main

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-lights-api-${{ matrix.arch }}-${{ hashFiles('**/go.sum') }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-lights-api-${{ matrix.arch }}-${{ hashFiles('**/go.sum') }}
            ${{ runner.os }}-lights-api-${{ matrix.arch }}
            ${{ runner.os }}-lights-api
      - run: GOARCH=${{ matrix.arch }} go build -o ./lights-api.linux-${{ matrix.arch }}
        working-directory: api
      - uses: actions/upload-artifact@v2
        with:
          name: lights-api.linux-${{ matrix.arch }}
          path: ${{ github.workspace }}/api/lights-api.linux-${{ matrix.arch }}
